version: '3.10'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./app/templates:/app/templates
      - ./app/DataBase.db:/app/DataBase.db
    command: flask run --host=0.0.0.0 --port=5000
